# Generated by Django 3.2.4 on 2021-10-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211002_1554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
