# Generated by Django 3.2.4 on 2021-10-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_userhashingpassword_pswd'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhashingpassword',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userhashingpassword',
            name='pswd',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='userhashingpassword',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
